---
- name: Install Elastic RPM
  yum:
    name: "{{ elastic_rpm }}"
    state: latest
  notify: elastic_service_restart

- name: Install Kibana RPM
  yum:
    name: "{{ kibana_rpm }}"
    state: latest
  when: ansible_hostname in kibana_nodes
  notify: kibana_service_restart

- name: Copy elasticsearch.yml template
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: elastic_service_restart

- name: Copy kibana.yml template
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  when: ansible_hostname in kibana_nodes
  notify: kibana_service_restart

- name: Copy Elastic Firewall Service
  template:
    src: elastic.xml.j2
    dest: /etc/firewalld/services/elastic.xml
    owner: root
    group: root
    mode: 0644

- name: Copy Kibana Firewall Service
  template:
    src: kibana.xml.j2
    dest: /etc/firewalld/services/kibana.xml
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname in kibana_nodes

- name: Reload Firewall to register new services
  shell: firewall-cmd --reload

- name: Open firewall for ElasticSearch
  firewalld:
    service: elastic
    state: enabled
    permanent: yes
    immediate: yes

- name: Open firewall for Kibana
  firewalld:
    service: kibana
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_hostname in kibana_nodes
  
- name: Copy JVM.Options template
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660
  when: ansible_hostname in kibana_nodes and ansible_hostname in master_nodes

- name: Create certs folder
  file:
    path: /etc/elasticsearch/certs
    state: directory
    owner: root
    group: elasticsearch
    mode: 0750

- name: Copy Cert file to hosts
  copy:
    src: randalllabs
    dest: /etc/elasticsearch/certs/randalllabs
    owner: root
    group: elasticsearch
    mode: 0640

- name: Enable ElasticSearch Service
  service: 
    name: "{{ elastic_service }}"
    state: started
    enabled: yes

- name: Enable Kibana Service
  service: 
    name: "{{ kibana_service }}"
    state: started
    enabled: yes
  when: ansible_hostname in kibana_nodes
