---
- name: Install Elastic RPM
  yum:
    name: "{{ elastic_rpm }}"
    state: latest
  when: install_elastic

- name: Install Kibana RPM
  yum:
    name: "{{ kibana_rpm }}"
    state: latest
  when: install_kibana

- name: Copy elasticsearch.yml template
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
