---
- name: Install Elastic RPM
  yum:
    name: "{{ elastic_rpm }}"
    state: latest
  when: install_elastic

- name: Install Kibana RPM
  yum:
    name: "{{ kibana_rpm }}"
    state: latest
  when: install_kibana
