---
- name: elastic_service_restart
  service:
    name: "{{ elastic_service }}"
    state: restarted
    enabled: yes

- name: kibana_service_restart
  service:
    name: "{{ kibana_service }}"
    state: restarted
    enabled: yes
